project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - proposal.qmd
    - data.qmd
    - methodology.qmd
    - insights.qmd
    - poster.qmd

website:
  title: "IS428"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Data
        href: data.qmd
      - text: Methodology
        href: methodology.qmd
      - text: Insights
        href: insights.qmd
      - text: Poster
        href: poster.qmd
  page-footer:
    left: "MC1 | Visual Analytics Project"
    right: "Authors: Hann Danish, Leong Rui Tao, Ethan Tay Fu Wen"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
